In [28]:
# MERGING
import numpy as np
import pandas as pd

In [29]:

frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],'color': ['white','red','red','black','green'],'brand': ['OMG','ABC','ABC','POD','POD']})

frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [30]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],'brand': ['OMG','POD','ABC','POD']})
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [31]:
pd.merge(frame1, frame2, on='id')

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [32]:
pd.merge(frame1, frame2, on='brand')

id_x  color brand    id_y
0     ball  white   OMG  pencil
1   pencil    red   ABC    ball
2      pen    red   ABC    ball
3      mug  black   POD  pencil
4      mug  black   POD     pen
5  ashtray  green   POD  pencil
6  ashtray  green   POD     pen

In [33]:
pd.merge(frame1, frame2) # empty merge, no sabe por donde unirlos y si no se aclara no se puede- en este caso siempre se excluyen valores

Empty DataFrame
Columns: [id, color, brand]
Index: []

In [37]:
# si las columnas tienen distintos nombres
frame2.columns = ['brand', 'sid']
print(frame1)
frame2

        id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD


brand  sid
0  pencil  OMG
1  pencil  POD
2    ball  ABC
3     pen  POD

In [39]:
pd.merge(frame1, frame2, left_on='id', right_on= 'brand')

id  color brand_x brand_y  sid
0    ball  white     OMG    ball  ABC
1  pencil    red     ABC  pencil  OMG
2  pencil    red     ABC  pencil  POD
3     pen    red     ABC     pen  POD

In [46]:
# outer join
frame2.columns = ['id', 'brand']
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [47]:
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [50]:
pd.merge(frame1, frame2, on='id') # por default hace un innerjoin

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [51]:
pd.merge(frame1, frame2, on='id', how='outer') # outer join junta todo aunque queden huecos, el frame 2 no tiene mug o ashtray

id  color brand_x brand_y
0     ball  white     OMG     ABC
1   pencil    red     ABC     OMG
2   pencil    red     ABC     POD
3      pen    red     ABC     POD
4      mug  black     POD     NaN
5  ashtray  green     POD     NaN

In [56]:
pd.merge(frame1, frame2, on='id', how='left')

id  color brand_x brand_y
0     ball  white     OMG     ABC
1   pencil    red     ABC     OMG
2   pencil    red     ABC     POD
3      pen    red     ABC     POD
4      mug  black     POD     NaN
5  ashtray  green     POD     NaN

In [57]:
pd.merge(frame1, frame2, on='id', how='right')

id  color brand_x brand_y
0  pencil    red     ABC     OMG
1  pencil    red     ABC     POD
2    ball  white     OMG     ABC
3     pen    red     ABC     POD

In [60]:
#merge on index
pd.merge(frame1,frame2,right_index=True, left_index=True)

id_x  color brand_x    id_y brand_y
0    ball  white     OMG  pencil     OMG
1  pencil    red     ABC  pencil     POD
2     pen    red     ABC    ball     ABC
3     mug  black     POD     pen     POD

In [62]:
# join() hace la union sobre índices independiente de las columnas
frame2.columns = ['brand2','id2']# join no cambia los nombres, la col no pueden tener los mismos nombres, usa el índice máximo
frame1.join(frame2)

id  color brand  brand2  id2
0     ball  white   OMG  pencil  OMG
1   pencil    red   ABC  pencil  POD
2      pen    red   ABC    ball  ABC
3      mug  black   POD     pen  POD
4  ashtray  green   POD     NaN  NaN

In [65]:
#concatenation
array1 = np.arange(9).reshape((3,3))
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
array2 = np.arange(9).reshape((3,3))+6
array2

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [67]:
np.concatenate([array1,array2], axis=1) #axis=1 sobre filas, axis=0 sobre col

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14]])

In [68]:
np.concatenate([array1,array2], axis=0) #axis=1 sobre filas(join horizontal), axis=0 sobre col (join vertial)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [69]:
ser1 = pd.Series(np.random.rand(4), index=[1,2,3,4])
ser2 = pd.Series(np.random.rand(4), index=[5,6,7,8])

In [71]:
pd.concat([ser1, ser2]) # concat vertical

1    0.671025
2    0.985947
3    0.202918
4    0.424946
5    0.046835
6    0.375672
7    0.778975
8    0.413892
dtype: float64

In [73]:
pd.concat([ser1, ser2], axis=1).fillna(0) # concat horizontal , por tener distinto index quedan vacíos

0         1
1  0.671025  0.000000
2  0.985947  0.000000
3  0.202918  0.000000
4  0.424946  0.000000
5  0.000000  0.046835
6  0.000000  0.375672
7  0.000000  0.778975
8  0.000000  0.413892

In [75]:
# para crear un índice jerárquico se puede agregar un key que abarque la col 0 y la col 1
pd.concat([ser1, ser2], keys=[1,2])

1  1    0.671025
   2    0.985947
   3    0.202918
   4    0.424946
2  5    0.046835
   6    0.375672
   7    0.778975
   8    0.413892
dtype: float64

In [77]:
pd.concat([ser1, ser2], keys=[1,2], axis=1).fillna(0) # los keys son las columnas

1         2
1  0.671025  0.000000
2  0.985947  0.000000
3  0.202918  0.000000
4  0.424946  0.000000
5  0.000000  0.046835
6  0.000000  0.375672
7  0.000000  0.778975
8  0.000000  0.413892

In [78]:
# same logic can be applied to DataFrames
frame1 = pd.DataFrame(np.random.rand(9).reshape(3,3), index=[1,2,3], columns=['A','B','C'])
frame2 = pd.DataFrame(np.random.rand(9).reshape(3,3), index=[4,5,6], columns=['A','B','C'])

In [79]:
frame1

A         B         C
1  0.643427  0.897128  0.376775
2  0.100464  0.440595  0.014493
3  0.164319  0.041783  0.126053

In [80]:
frame2

A         B         C
4  0.228308  0.768416  0.773075
5  0.807345  0.762978  0.303605
6  0.414524  0.688334  0.418846

In [82]:
pd.concat([frame1, frame2])

A         B         C
1  0.643427  0.897128  0.376775
2  0.100464  0.440595  0.014493
3  0.164319  0.041783  0.126053
4  0.228308  0.768416  0.773075
5  0.807345  0.762978  0.303605
6  0.414524  0.688334  0.418846

In [83]:
pd.concat([frame1, frame2], axis=1)

A         B         C         A         B         C
1  0.643427  0.897128  0.376775       NaN       NaN       NaN
2  0.100464  0.440595  0.014493       NaN       NaN       NaN
3  0.164319  0.041783  0.126053       NaN       NaN       NaN
4       NaN       NaN       NaN  0.228308  0.768416  0.773075
5       NaN       NaN       NaN  0.807345  0.762978  0.303605
6       NaN       NaN       NaN  0.414524  0.688334  0.418846

In [84]:
# pivoting
frame1 = pd.DataFrame(np.arange(9).reshape(3,3),index=['white','black','red'],columns=['ball','pen','pencil'])
frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [86]:
# stack returns the pivoting of the columns
ser5 = frame1.stack()
ser5

white  ball      0
       pen       1
       pencil    2
black  ball      3
       pen       4
       pencil    5
red    ball      6
       pen       7
       pencil    8
dtype: int32

In [88]:
ser5 = ser5.unstack()
ser5

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [94]:
#tambien se puede unstack en distintos niveles
ser5 = frame1.stack()
ser5 = ser5.unstack(0) # unstack 0 transpone la matriz original, el 1 re-obtiene la matrz original
ser5

white  black  red
ball        0      3    6
pen         1      4    7
pencil      2      5    8

In [95]:
# pivoting from long to wide format
longframe = pd.DataFrame({ 'color':['white','white','white','red','red','red','black','black','black'],'item':['ball','pen','mug','ball','pen','mug','ball','pen','mug'],'value': np.random.rand(9)})

longframe


color  item     value
0  white  ball  0.201712
1  white   pen  0.335209
2  white   mug  0.557915
3    red  ball  0.282916
4    red   pen  0.033609
5    red   mug  0.637897
6  black  ball  0.723713
7  black   pen  0.190128
8  black   mug  0.884715

In [101]:
# wideframe = pivot() permite transformar una de la columnas en fila(sus valores) y la columna (sus valores) y dentro están los value
wideframe = longframe.pivot('color', 'item') # el primer término pasa a index y el segundo a columna
wideframe

value                    
item       ball       mug       pen
color                              
black  0.723713  0.884715  0.190128
red    0.282916  0.637897  0.033609
white  0.201712  0.557915  0.335209

In [103]:
del longframe['color']
longframe

item     value
0  ball  0.201712
1   pen  0.335209
2   mug  0.557915
3  ball  0.282916
4   pen  0.033609
5   mug  0.637897
6  ball  0.723713
7   pen  0.190128
8   mug  0.884715

In [105]:
longframe.drop(0) # se quita con drop() el row - sea nro de indice o nombre del valor

item     value
1   pen  0.335209
2   mug  0.557915
3  ball  0.282916
4   pen  0.033609
5   mug  0.637897
6  ball  0.723713
7   pen  0.190128
8   mug  0.884715

In [106]:
# DATA TRANSFORMATION - removing duplicates
dframe = pd.DataFrame({ 'color': ['white','white','red','red','white'],'value': [2,1,3,3,2]})

dframe

color  value
0  white      2
1  white      1
2    red      3
3    red      3
4  white      2

In [108]:
dframe.duplicated()

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [109]:
dframe[dframe.duplicated()] # se quedan solamente los duplicados white y 2

color  value
3    red      3
4  white      2

In [111]:
dframe.drop_duplicates() # quita todos los valores duplicados

color  value
0  white      2
1  white      1
2    red      3

In [112]:
# mapping 
"""
replace() - replaces values
map() - creates a new column
rename() - replaces the index values
"""

'\nreplace()\nmap()\nrename()\n'

In [113]:
frame = pd.DataFrame({ 'item':['ball','mug','pen','pencil','ashtray'],'color':['white','rosso','verde','black','yellow'], 'price':[5.56,4.20,1.30,0.56,2.75]})

frame

item   color  price
0     ball   white   5.56
1      mug   rosso   4.20
2      pen   verde   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [115]:
# replace with new colors store in a dict
new_colors = {
    'rosso': 'red',
    'verde':'green'
}

frame.replace(new_colors)

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [120]:
frame = pd.DataFrame({ 'item':['ball','mug','pen','pencil','ashtray'],'color':['white','red','green','black','yellow']})

# si se quiere pasar otra columna con nuevos valores se arma un diccionario que tenga keys en comun con una de la columnas
prices = { 'ball' : 5.56,
'mug' : 4.20,
'bottle' : 1.30,
'scissors' : 3.41,
'pen' : 1.30,
'pencil' : 0.56,
'ashtray' : 2.75
         }
frame['price'] = frame['item'].map(prices) # el map acepta una función o un diccionario que mapear
frame

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [126]:
new_index = {
    0: 'first',
    1: 'second',
    2: 'third',
    3: 'fourth',
    4: 'fifth'
}
frame.rename(new_index)

item   color  price
first      ball   white   5.56
second      mug     red   4.20
third       pen   green   1.30
fourth   pencil   black   0.56
fifth   ashtray  yellow   2.75

In [128]:
re_column= {
    'item': 'object',
    'price': 'value' 
}

frame.rename(columns=re_column, index=new_index)

object   color  value
first      ball   white   5.56
second      mug     red   4.20
third       pen   green   1.30
fourth   pencil   black   0.56
fifth   ashtray  yellow   2.75

In [130]:
# rename crea un nuevo df dejando el original unchanged, para cambiar el objeto original se coloca inplace= True
frame.rename(columns={'item':'object'}, inplace=True)
frame


object   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [134]:
# discret and bining
results = [12,34,67,55,28,90,99,12,3,56,74,44,87,23,49,89,87]
bins = [0, 25, 50, 75, 100] # queremos separar el rango de valores en 4

cat = pd.cut(results, bins)
cat # transforma los valores en un rango de bins

[(0, 25], (25, 50], (50, 75], (50, 75], (25, 50], ..., (75, 100], (0, 25], (25, 50], (75, 100], (75, 100]]
Length: 17
Categories (4, interval[int64]): [(0, 25] < (25, 50] < (50, 75] < (75, 100]]

In [135]:
cat.categories # devuelve los tipos de bins

IntervalIndex([(0, 25], (25, 50], (50, 75], (75, 100]],
              closed='right',
              dtype='interval[int64]')

In [136]:
cat.codes # asigna un código a cada bin y muestra cuántas veces aparece

array([0, 1, 2, 2, 1, 3, 3, 0, 0, 2, 2, 1, 3, 0, 1, 3, 3], dtype=int8)

In [137]:
# para saber lo ocurrencia de c/u
pd.value_counts(cat)

(75, 100]    5
(50, 75]     4
(25, 50]     4
(0, 25]      4
dtype: int64

In [139]:
bin_names = ['unlikely','less likely','likely','highly likely']
cat = pd.cut(results, bins, labels=bin_names) # asigna nombres a los bins
pd.value_counts(cat)

highly likely    5
likely           4
less likely      4
unlikely         4
dtype: int64

In [144]:
# también se puede cortar en bins de un dado tamanio
pd.cut(results, 5).value_counts()


(2.904, 22.2]    3
(22.2, 41.4]     3
(41.4, 60.6]     4
(60.6, 79.8]     2
(79.8, 99.0]     5
dtype: int64

In [153]:
# para dividir la muestra en quintilos, decilos, etc qcut(), siendo el segundo término la cantidad de divisiones
quintiles = pd.qcut(results, 5)
quintiles.value_counts()

(2.999, 24.0]    4
(24.0, 46.0]     3
(46.0, 62.6]     3
(62.6, 87.0]     4
(87.0, 99.0]     3
dtype: int64

In [161]:
# DETECTING AND FILTERING OUTLIERS
randframe = pd.DataFrame(np.random.randn(1000,3)) # mil nros al azar divididos en trres columnas
randframe

0         1         2
0    0.351626 -0.711269  0.403451
1   -1.322693  0.003234 -0.653112
2   -0.165504 -0.079892  0.695636
3   -0.868914  0.544261  0.674567
4    0.187743  0.936727  1.312996
..        ...       ...       ...
995 -0.284348 -2.109135  1.913940
996 -0.446035  0.693399 -0.570444
997  1.666116  0.065914 -0.431960
998  1.218353 -0.321359  0.686416
999 -0.279839 -1.856488 -1.019949

[1000 rows x 3 columns]

In [162]:
randframe.std()

0    0.999223
1    1.010507
2    0.989225
dtype: float64

In [165]:
randframe.mean()

0    0.000594
1   -0.013673
2    0.002263
dtype: float64

In [173]:
randframe[(np.abs(randframe) > (3*randframe.std())).any(1)] #any 1 se eplica a todas la columnas

0         1         2
46   3.900392  1.285533 -0.256228
65  -0.259205  0.272581  3.186427
214  0.999832  1.465279  2.993721
350  0.998401 -0.051412 -3.290563
809 -0.019876 -3.065351  0.968811
881  0.478138 -3.142523 -1.303135
978 -0.194624  3.302970  1.020419

In [174]:
# PERMUTATION
nframe = pd.DataFrame(np.arange(25).reshape(5,5))
nframe

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [177]:
new_order = np.random.permutation(5)
new_order

array([3, 0, 4, 2, 1])

In [178]:
# podemos usar la funcion take() para asignar los valores índice con los valores new_order
nframe.take(new_order)

0   1   2   3   4
3  15  16  17  18  19
0   0   1   2   3   4
4  20  21  22  23  24
2  10  11  12  13  14
1   5   6   7   8   9

In [179]:
# también se pueden filtrar los rows pasando index discretos
nframe.take([1,3,4])

0   1   2   3   4
1   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24

In [184]:
# random sampling np.random.randit() - selecciona valores al azar de un df
sample = np.random.randint(0, len(nframe), size=3) # len(nframe) refiere al nro de col y size al de rows
nframe.take(sample)

0   1   2   3   4
3  15  16  17  18  19
1   5   6   7   8   9
0   0   1   2   3   4

In [185]:
# DATA AGGREGATION
'''
ejemplo son count(), sum(), mean() - hacen operaciones que afectan a toda la matriz y devuelve un nro no una matriz-
group_by():
         .splitting() -divisions into groups 
         .applying() - app de una funcion en cada grupo
         .combining() - combinar de todos los resultados por diferentes grupos
    
'''
frame = pd.DataFrame({ 'color': ['white','red','green','red','green'],'object': ['pen','pencil','pencil','ashtray','pen'],'price1' : [5.56,4.20,1.30,0.56,2.75],'price2' : [4.75,4.12,1.60,0.75,3.15]})
frame

color   object  price1  price2
0  white      pen    5.56    4.75
1    red   pencil    4.20    4.12
2  green   pencil    1.30    1.60
3    red  ashtray    0.56    0.75
4  green      pen    2.75    3.15

In [187]:
# si queremos agrupar los price1 y usar los color como label podos usar el groupby
group = frame['price1'].groupby(frame['color'])
group # genera un gropu object

In [188]:
group.mean() # devuelve el promedio del precio1 para cada color

color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64

In [189]:
group.sum()

color
green    4.05
red      4.76
white    5.56
Name: price1, dtype: float64

In [194]:
# se puede establecer una jerarquía de agrupamiento usando disintas columnas como agrupadores
ggroup = frame['price1'].groupby([frame['color'], frame['object']])
ggroup.mean()

color  object 
green  pen        2.75
       pencil     1.30
red    ashtray    0.56
       pencil     4.20
white  pen        5.56
Name: price1, dtype: float64

In [195]:
ggroup.sum()

color  object 
green  pen        2.75
       pencil     1.30
red    ashtray    0.56
       pencil     4.20
white  pen        5.56
Name: price1, dtype: float64

In [196]:
frame[['price1','price2']].groupby(frame['color']).mean()  # también se puede llamar todas col valores de una y realizar el calculo aggreado de 1

price1  price2
color                
green   2.025   2.375
red     2.380   2.435
white   5.560   4.750

In [197]:
frame.groupby(frame['color']).mean() # sin aclarar las col de frame por default toma todas las col con nros

price1  price2
color                
green   2.025   2.375
red     2.380   2.435
white   5.560   4.750

In [198]:
frame.groupby('color').mean()

price1  price2
color                
green   2.025   2.375
red     2.380   2.435
white   5.560   4.750

In [199]:
# iteration over groups - quiero conocer los nombres y grupos
for name, groups in frame.groupby('color'):
    print(name) # título del grupo
    print(groups) # el grupo en cuestión


green
   color  object  price1  price2
2  green  pencil    1.30    1.60
4  green     pen    2.75    3.15
red
  color   object  price1  price2
1   red   pencil    4.20    4.12
3   red  ashtray    0.56    0.75
white
   color object  price1  price2
0  white    pen    5.56    4.75


In [200]:
# para hacerlo más legible podemos agregad el .add_prefix()
means = frame.groupby('color').mean().add_prefix('mean_')
means

mean_price1  mean_price2
color                          
green        2.025        2.375
red          2.380        2.435
white        5.560        4.750

In [204]:
# functions on groups
group = frame.groupby('color')
group['price1'].quantile(0.6)


color
green    2.170
red      2.744
white    5.560
Name: price1, dtype: float64

In [206]:
def range(series):
    return series.max() - series.min()

group['price1'].agg(range)

color
green    1.45
red      3.64
white    0.00
Name: price1, dtype: float64

In [207]:
group.agg(range)

price1  price2
color                
green    1.45    1.55
red      3.64    3.37
white    0.00    0.00

In [209]:
# también se pueden colocar un array de funciones que se convierten en las nuevas colmnas
group['price1'].agg(['mean','std',range]).fillna(0) # built in functions pasan como string

mean       std  range
color                        
green  2.025  1.025305   1.45
red    2.380  2.573869   3.64
white  5.560  0.000000   0.00

In [210]:
# advanced data aggregation
frame = pd.DataFrame({ 'color':['white','red','green','red','green'],'price1':[5.56,4.20,1.30,0.56,2.75],'price2':[4.75,4.12,1.60,0.75,3.15]})
frame

color  price1  price2
0  white    5.56    4.75
1    red    4.20    4.12
2  green    1.30    1.60
3    red    0.56    0.75
4  green    2.75    3.15

In [219]:
sums = frame.groupby(frame['color']).sum().add_prefix('tot_')
sums

tot_price1  tot_price2
color                        
green        4.05        4.75
red          4.76        4.87
white        5.56        4.75

In [225]:
import pandas as pd

In [227]:
pd.merge(frame, sums, left_on='color', right_index= True)

color  price1  price2  tot_price1  tot_price2
0  white    5.56    4.75        5.56        4.75
1    red    4.20    4.12        4.76        4.87
3    red    0.56    0.75        4.76        4.87
2  green    1.30    1.60        4.05        4.75
4  green    2.75    3.15        4.05        4.75

In [228]:
# transform function
frame.groupby('color').transform(np.sum).add_prefix('_tot')

_totprice1  _totprice2
0        5.56        4.75
1        4.76        4.87
2        4.05        4.75
3        4.76        4.87
4        4.05        4.75